baseURL = "https://hashnhedge.com/"
title = "Hash & Hedge"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "hugo-narrow"
enableRobotsTXT = true
[pagination]
  pagerSize = 12

[permalinks]
  posts = "/posts/:year/:month/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[services]
  [services.googleAnalytics]
    id = "G-4BD4Z2JKW3"

[params]
  tagline = "life in the grey makes you appreciate color in everything."
  # Theme expects author as table with name, avatar, etc.
  [params.author]
    name = "Hash & Hedge Newsroom"
    avatar = "/images/avatar.svg"
    title = "Hash & Hedge"
    description = "Daily AI, fintech, markets briefs"
  copyright = "© Hash & Hedge"
  logo = "/logo.svg"
  adsense_enabled = true
  adsense_publisher_id = "ca-pub-4626165154390205"
  adsense_inarticle_slot_id = "5837847046"
  consent_mode = true
  images = ["/logo.svg"]

[params.ga4]
  id = "G-4BD4Z2JKW3"
