baseURL = "https://hashnhedge.com/"
title = "Hash & Hedge"
languageCode = "en-us"
theme = "newsroom"

[pagination]
  pagerSize = 12

[params]
  author = "Hash & Hedge"
  description = "Cryptocurrency, finance, and security insights"
  
  # AdSense
  googleAdsenseID = "ca-pub-4626165154390205"
  enableAdsense = true
  
  # Analytics
  ga_analytics = "G-4BD4Z2JKW3"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Crypto"
  url = "/categories/crypto/"
  weight = 2

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[markup.goldmark.renderer]
  unsafe = true