baseURL = "https://hashnhedge.com/"
title = "Hash & Hedge"
languageCode = "en-us"
theme = "newsroom"

[pagination]
  pagerSize = 12

[params]
  description = "Cryptocurrency, finance, and security insights for smart investors"
  author = "Hash & Hedge"
  tagline = "life in the grey makes you appreciate color in everything"
  
  # Site features
  shareInFooter = true
  scrollToTop = true
  enableSidebar = true
  showRelated = true
  
  # Images
  logo = "/images/logo.png"
  favicon = "/favicon.ico"
  defaultImage = "/images/default-hero.jpg"
  
  # AdSense Configuration
  googleAdsenseID = "ca-pub-4626165154390205"
  adsenseSlot = "1234567890"
  showAds = true
  
  # Google Analytics
  ga_analytics = "G-4BD4Z2JKW3"
  
  # SEO
  keywords = "cryptocurrency, bitcoin, finance, investing, security, blockchain, defi, trading"
  ogImage = "/images/og-default.jpg"
  twitterCard = "summary_large_image"
  twitterHandle = "@hashnhedge"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Crypto"
  url = "/categories/crypto/"
  weight = 2

[[menu.main]]
  name = "Finance"
  url = "/categories/finance/"
  weight = 3

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS"]

[markup.goldmark.renderer]
  unsafe = true