baseURL = "https://hashnhedge.com/"
title = "Hash & Hedge"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "hugo-narrow"

[module]
  [[module.imports]]
    path = "github.com/cowboysmall-tools/hugo-narrow"
    version = "v1.1.3"
enableRobotsTXT = true

[pagination]
  pagerSize = 12

[permalinks]
  posts = "/posts/:year/:month/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[services]
  [services.googleAnalytics]
    id = "G-4BD4Z2JKW3"

[params]
  tagline = "life in the grey makes you appreciate color in everything."
  # Remove author table to hide the large author block on the homepage
  # (post pages will gracefully default without author metadata)
  copyright = "© Hash \u0026 Hedge"
  logo = "/logo.svg"
  adsense_enabled = true
  adsense_publisher_id = "ca-pub-4626165154390205"
  adsense_inarticle_slot_id = "5837847046"
  # Disable intrusive consent banner
  consent_mode = false
  images = ["/logo.svg"]
  
  # Home settings
  [params.home]
    recentPostsCount = 20

[params.ga4]
  id = "G-4BD4Z2JKW3"
