baseURL = 'https://hashnhedge.com/'
languageCode = 'en-us'
title = 'Hash & Hedge - Smart Financial Insights'
theme = 'newsroom'
summaryLength = 25
canonifyURLs = true
relativeURLs = false

# Pagination settings - Infinite scroll with 20 posts per page
[pagination]
  pagerSize = 20

# Enable RSS and JSON feeds - Add JSON for infinite scroll API
[outputs]
  home = ["HTML", "RSS", "JSON", "AMP"]
  page = ["HTML", "JSON", "AMP"]
  section = ["HTML", "RSS", "JSON", "AMP"]

# AMP Output Format Configuration
[outputFormats.AMP]
  mediaType = "text/html"
  path = "amp"
  isPlainText = false
  permalinkable = true
  noUgly = true

# Google Analytics and AdSense
[params]
  description = "Discover smart financial strategies, crypto insights, and money-saving tips for building wealth on any budget"
  author = "Hash & Hedge Team"
  keywords = ["cryptocurrency", "bitcoin", "ethereum", "finance", "investing", "defi", "trading", "financial advice"]
  logo = "/images/hash-hedge-main-logo.svg"
  
  # AdSense Configuration - ACTIVE
  googleAdsenseID = "ca-pub-4626165154390205"  # Your verified AdSense ID
  enableAdsense = true
  
  # Analytics - Active GA4 Tracking
  ga_analytics = "G-4BD4Z2JKW3"  # Your GA4 Measurement ID - Analytics Active!
  
  # Social links
  twitter = "hashnhedge"
  github = "knol3j"
  
  # Site features
  showDate = true
  showTags = true
  showSummary = true
  showReadingTime = true
  
  # Newsroom theme specific settings with professional brand focus
  homeIntroTitle = "Hash & Hedge"
  homeIntroContent = "Smart financial insights for the crypto era. Join CryptoHedgey, our spiky mascot, as we navigate the complex world of cryptocurrency and finance with sharp analysis and practical advice"
  
  # SEO enhancements
  enableOpenGraph = true
  enableTwitterCards = true
  enableSchema = true
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Market News"
  url = "/categories/markets/"
  weight = 2

[[menu.main]]
  name = "Analysis"
  url = "/categories/analysis/"
  weight = 3

[[menu.main]]
  name = "DeFi"
  url = "/tags/defi/"
  weight = 4

# Footer menu for secondary pages
[[menu.footer]]
  name = "About"
  url = "/about/"
  weight = 1

[[menu.footer]]
  name = "Contact"
  url = "/contact/"
  weight = 2

[[menu.footer]]
  name = "Advertise"
  url = "/advertise/"
  weight = 3

[[menu.footer]]
  name = "Terms of Service"
  url = "/terms/"
  weight = 4

[[menu.footer]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 5

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"
  coin = "coins"

# Permalinks
[permalinks]
  posts = "/:year/:month/:title/"

# Sitemap configuration
[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5
# Advanced SEO Configuration
[params.seo]
  enableJSONLD = true
  enableOpenGraph = true
  enableTwitterCards = true
  enableRobotsTXT = true
  enableSitemap = true

# Social Media and Verification
[params.verification]
  google = ""  # Add Google Search Console verification code
  bing = ""    # Add Bing Webmaster Tools verification code
  yandex = ""  # Add Yandex Webmaster verification code

# Performance and Security Headers
[params.security]
  enableCSP = true
  enableHSTS = true
  enableReferrerPolicy = true

# Advanced markup configuration

[markup.highlight]
  style = "github"
  lineNos = false
  codeFences = true
  guessSyntax = true
  hl_Lines = ""
  lineNumbersInTable = true
  noClasses = false
  tabWidth = 4

# Related content for better internal linking
[related]
  includeNewer = true
  threshold = 80
  toLower = false
  
  [[related.indices]]
    name = "keywords"
    weight = 100
  
  [[related.indices]]
    name = "tags"
    weight = 80
  
  [[related.indices]]
    name = "categories"
    weight = 60
  
  [[related.indices]]
    name = "date"
    weight = 10

# Image processing for optimization
[imaging]
  resampleFilter = "lanczos"
  quality = 85
  anchor = "smart"

[imaging.exif]
  includeFields = ""
  excludeFields = "GPS|Exif|IPTC|IFD|Photoshop"
  disableDate = false
  disableLatLong = true
