baseurl = "https://hashnhedge.com/"
title = "Hash & Hedge"
theme = "newsroom"
languageCode = "en-us"
canonifyurls = true
enableRobotsTXT = true

[pagination]
disableAliases = false
pagerSize = 12
path = 'page'

[permalinks]
posts = '/:year/:month/:slug/'
pages = ':contentbasename/'

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS"]

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
# Site Identity
blogDir = "posts"
mainSections = ["posts"]
logo = "/images/logo.svg"
faviconsDir = "images/icons/"
description = "Crypto, finance, and security through the lens of culture and craft. Concise, thoughtful stories with brutal honesty."
tagline = "life in the grey makes you appreciate color in everything"

# Social Media
twitter = "hashnhedge"
email = "ugbuni@proton.me"

# Analytics
ga_analytics = "G-4BD4Z2JKW3"

# AdSense Monetization
adsense_enabled = true
adsense_publisher_id = "ca-pub-4626165154390205"

# SEO Optimization
keywords = ["cryptocurrency", "bitcoin", "blockchain", "cybersecurity", "hacking", "finance", "market analysis", "crypto news"]

[services]
[services.googleAnalytics]
id = "G-4BD4Z2JKW3"

# Sitemap configuration
[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

# RSS configuration
[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"