name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout code WITHOUT submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.148.2'
          extended: true
      
      - name: Verify and Install Newsroom theme
        run: |
          echo "=== Theme Verification Phase ==="
          if [ -d "site/themes/newsroom/layouts" ]; then
            echo "✓ Theme detected: $(find site/themes/newsroom -type f | wc -l) files"
          else
            echo "✗ Theme missing - Installing from repository"
            git clone https://github.com/onweru/newsroom.git site/themes/newsroom
            rm -rf site/themes/newsroom/.git
            echo "✓ Theme installed successfully"
          fi
      
      - name: Build with Hugo (Corrected Command)
        run: |
          cd site
          echo "=== Hugo Build Phase ==="
          echo "Current directory: $(pwd)"
          echo "Hugo version: $(hugo version)"
          echo "Building site..."
          hugo --gc --minify --destination ../public
          cd ..
          echo "=== Build Verification ==="
          if [ -d "public" ]; then
            echo "✓ Build successful"
            echo "Files generated: $(find public -type f | wc -l)"
            echo "Total size: $(du -sh public | cut -f1)"
          else
            echo "✗ Build failed - public directory not created"
            exit 1
          fi
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4