name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout code WITHOUT submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false  # CRITICAL: Explicitly disable submodule processing
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.148.2'
          extended: true
      
      - name: Verify theme installation
        run: |
          echo "Verifying Newsroom theme presence..."
          if [ -d "site/themes/newsroom/layouts" ]; then
            echo "✓ Theme confirmed: $(ls -la site/themes/newsroom/ | wc -l) files"
          else
            echo "✗ Theme missing - emergency installation"
            git clone https://github.com/onweru/newsroom.git site/themes/newsroom
            rm -rf site/themes/newsroom/.git
          fi
      
      - name: Build with Hugo
        run: |
          cd site
          echo "Building site with Hugo..."
          hugo --gc --minify --destination ../public --verbose
          echo "Build complete: $(find ../public -type f | wc -l) files generated"
      
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4