name: Fetch hero images nightly

on:
  schedule:
    - cron: "15 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f pipeline/requirements.txt ]; then pip install -r pipeline/requirements.txt; else pip install requests beautifulsoup4 lxml python-frontmatter; fi
      - name: Run image fetcher
        run: python pipeline/fetch_images.py
      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "chore: nightly image fetch"
            git push
          else
            echo "No changes."
          fi
