name: Daily Content Publishing

on:
  schedule:
    # 9 AM UTC (adjust for your timezone)
    - cron: "0 9 * * *"
    # 12 PM (noon) UTC
    - cron: "0 12 * * *"
    # 5 PM UTC
    - cron: "0 17 * * *"
  workflow_dispatch:
    inputs:
      post_count:
        description: 'Number of posts to generate'
        required: false
        default: '1'

permissions:
  contents: write

jobs:
  publish-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r pipeline/requirements.txt
          pip install python-frontmatter requests beautifulsoup4 lxml

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.148.2'
          extended: true

      - name: Generate new content
        run: |
          # Determine post count (1 for scheduled runs, custom for manual)
          POST_COUNT="${{ github.event.inputs.post_count || '1' }}"
          
          # Run the content generation pipeline
          cd pipeline
          python generate_posts.py --count $POST_COUNT --auto-commit false
          cd ..

      - name: Fetch images for new posts
        run: |
          python pipeline/fetch_images.py
      - name: Commit and push changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            HOUR=$(date -u +%H)
            case $HOUR in
              09) TIME_LABEL="Morning" ;;
              12) TIME_LABEL="Noon" ;;
              17) TIME_LABEL="Evening" ;;
              *) TIME_LABEL="Manual" ;;
            esac
            git commit -m "feat: $TIME_LABEL content drop - $(date -u +%Y-%m-%d)"
            git push
          else
            echo "No changes to commit"
          fi

      - name: Trigger site rebuild
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'site.yml',
              ref: 'main'
            })

      - name: Health check notification
        if: success()
        run: |
          echo "✅ Content published successfully at $(date -u)"