name: Scheduled Jekyll Post Publisher

on:
  schedule:
    # 9 AM UTC
    - cron: "0 9 * * *"
    # 12 PM UTC
    - cron: "0 12 * * *"
    # 5 PM UTC
    - cron: "0 17 * * *"
  workflow_dispatch:
    inputs:
      post_count:
        description: Number of posts to generate (default 3)
        required: false
        default: "3"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pipeline dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f pipeline/requirements.txt ]; then pip install -r pipeline/requirements.txt; fi

      - name: Generate curated Jekyll posts
        env:
          POST_COUNT: ${{ github.event.inputs.post_count || '3' }}
        run: |
          python pipeline/generate_jekyll_posts.py --count "$POST_COUNT"
          echo "POST_COUNT=$POST_COUNT" >> "$GITHUB_ENV"

      - name: Commit and push if changes
        shell: bash
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            HOUR=$(date -u +%H)
            case $HOUR in
              09) TIME_LABEL="Morning" ;;
              12) TIME_LABEL="Noon" ;;
              17) TIME_LABEL="Evening" ;;
              *) TIME_LABEL="Manual" ;;
            esac
            git commit -m "feat(content): $TIME_LABEL curated posts (x${{ env.POST_COUNT }}) - $(date -u +%Y-%m-%d)"
            git push
          else
            echo "No changes to commit"
          fi

